# Generated by Django 5.2.3 on 2025-06-25 11:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='temp-slug', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
